practiceSite/dashBoardProvost/urls.py
from django.urls import path
from . import views

app_name = 'dashBoardProvost'

urlpatterns = [
    path('', views.IndexView.as_view(), name='provostIndex'),
    path('upload/', views.modelFormUpload, name='upload'),
    path('login/', views.login_view, name='login_view'),
    path('logged_in/', views.logged_in, name='logged_in'),
    path('InitializeHostelForm/',views.InitializeHostelView,name='InitializeHostelForm'),
    path('Allotment/',views.AllotmentView,name='Allotment')
]

practiceSite/dashBoardStudent/urls.py
# from django.conf.urls import url
from django.urls import path
from dashBoardStudent import views

from . import views

app_name='dashBoardStudent'

urlpatterns=[
    path('login/', views.login_view, name='login_view'),
    path('logged_in/', views.logged_in, name='logged_in'),
    # path('', views.index, name='studentIndex')
]

practiceSite/homepage/urls.py
from django.urls import path
from . import views
app_name='homepage'

urlpatterns=[
    path('',views.IndexView.as_view(),name='index')
]

practiceSite/practiceSite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url,include
from django.views.generic import RedirectView
from dashBoardStudent import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    #path('',RedirectView.as_view(url='/accounts/login')),
    #path('admin/', admin.site.urls),
    #path('accounts/',include('django.contrib.auth.urls')),
    # path('polls/', include('polls.urls')),
    #path('fileUploads/',include('fileUploads.urls'))

    #url(r'^dashBoardStudent/$', include(dashBoardStudent.urls))
    path('admin/', admin.site.urls),
    path('dashBoardStudent/', include('dashBoardStudent.urls')),
    path('dashBoardProvost/', include('dashBoardProvost.urls')),
    path('', RedirectView.as_view(url='/homepage/')),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('polls/', include('polls.urls')),
    path('fileUploads/', include('fileUploads.urls')),
    path('homepage/', include('homepage.urls'))
]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

practiceSite/homepage/models.py
from django.db import models

# Create your models here.

practiceSite/homepage/views.py
from django.shortcuts import render
from django.views import generic
# Create your views here.

class IndexView(generic.TemplateView):
    template_name = 'homepage/index.html'

practiceSite/homepage/templates/homepage/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Home Page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- <link rel="stylesheet" type="text/css" media="screen" href="main.css" /> -->
    <!-- <script src="main.js"></script> -->
</head>
<style>
    a{
        text-decoration: none;
        color: #000000
    }
    body{
        color: white;
        height: 100%;
        background-image: url("/media/back3.jpg");
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
    }
    body,html{
        height: 100%;
    }
    .cr{
        text-align: center;
        /* margin-top: 15%; */
    }
    .crr{
        display: inline-block;
    }
</style>
<body>
    <div class="container cr">
        <div class="container-fluid crr" style="margin-top :10%">
            <div class="cr">
                <img src="/media/favicon.png" alt="logo" class="img-responsive crr">
            </div>
            <h1>Welcome</h1>
                <a href="{% url 'dashBoardProvost:login_view' %}">
                    <button>Provost Login</button>
                </a>
                <!-- <a href="{url '/app/template_login.html'}">
                    <button>Warden Login</button>
                </a> -->
                <a href="{% url 'dashBoardStudent:login_view' %}">
                    <button>Student Login</button>>
                </a>
        </div>
    </div>
</body>
</html>