practiceSite/dashBoardProvost/urls.py
from django.urls import path
from . import views

app_name = 'dashBoardProvost'

urlpatterns = [
    path('', views.IndexView.as_view(), name='provostIndex'),
    path('upload/', views.modelFormUpload, name='upload'),
    path('login/', views.login_view, name='login_view'),
    path('logged_in/', views.logged_in, name='logged_in'),
    path('InitializeHostelForm/',views.InitializeHostelView,name='InitializeHostelForm'),
    path('Allotment/',views.AllotmentView,name='Allotment')
]

practiceSite/fileUploads/urls.py
from django.urls import path
from . import views
app_name = 'fileUploads'
urlpatterns = [
    path('',views.IndexView.as_view(),name = 'index'),
    path('upload/',views.modelFormUpload, name = 'upload'),
]

practiceSite/homepage/urls.py
from django.urls import path
from . import views
app_name='homepage'

urlpatterns=[
    path('',views.IndexView.as_view(),name='index')
]

practiceSite/practiceSite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url,include
from django.views.generic import RedirectView
from dashBoardStudent import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    #path('',RedirectView.as_view(url='/accounts/login')),
    #path('admin/', admin.site.urls),
    #path('accounts/',include('django.contrib.auth.urls')),
    # path('polls/', include('polls.urls')),
    #path('fileUploads/',include('fileUploads.urls'))

    #url(r'^dashBoardStudent/$', include(dashBoardStudent.urls))
    path('admin/', admin.site.urls),
    path('dashBoardStudent/', include('dashBoardStudent.urls')),
    path('dashBoardProvost/', include('dashBoardProvost.urls')),
    path('', RedirectView.as_view(url='/homepage/')),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('polls/', include('polls.urls')),
    path('fileUploads/', include('fileUploads.urls')),
    path('homepage/', include('homepage.urls'))
]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

practiceSite/dashBoardProvost/models.py
from django.db import models
from django.contrib.auth.models import User



class Document(models.Model):
    file = models.FileField(upload_to='documents/')

class dataModel(models.Model):
    fname = models.CharField(max_length=120)
    lname = models.CharField(max_length=120)


class studentModel(models.Model):
    eNo = models.CharField(max_length=6)
    Name = models.CharField(max_length=120)
    FacNo = models.CharField(max_length=10)
    current_standing = models.IntegerField(default=0)
    # room = models.OneToOneField(roomModel,blank=True, on_delete=models.CASCADE)
    # room = models.ManyToManyField(roomModel)


class roomModel(models.Model):
    hostel = models.CharField(max_length=120)
    seater = models.IntegerField()
    room_no= models.IntegerField()
    seat_no = models.IntegerField()
    student = models.OneToOneField(studentModel, on_delete=models.CASCADE, null = True)
    vacant = models.BooleanField()
    



    
# class studentModel(models.Model):
    # eNo = models.CharField(max_length=6)
    # Name = models.CharField(max_length=120)
    # FacNo = models.CharField(max_length=10)
    # current_standing = models.IntegerField(default=0)
    # room = models.ForeignKey(roomModel,on_delete=models.CASCADE,related_name='roomAlloted',blank=True)
    # abcd = models.CharField(max_length = 120)

practiceSite/dashBoardProvost/forms.py
from django import forms
from .models import Document,dataModel

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('file', )

class dataModelForm(forms.ModelForm):
    class Meta:
        model=dataModel
        fields = "__all__"

class InitializeHostelForm(forms.Form):
    hostel_name = forms.CharField(max_length=120)
    numberOfRooms = forms.IntegerField()
    seater = forms.IntegerField()

practiceSite/dashBoardProvost/views.py
from django.shortcuts import render
import csv
import os
from django.views import generic
from .forms import DocumentForm,dataModelForm,InitializeHostelForm
from .models import dataModel,roomModel,studentModel
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from dashBoardStudent.models import UserLogin

from django.conf import settings
# Create your views here.
# @login_required


# @method_decorator(login_required, name='dispatch')
class IndexView(generic.TemplateView):
    template_name = 'dashBoardProvost/dashboard.html'

def dispath(request):
    return render(request,"Please Login to the system")

@login_required
def modelFormUpload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.info(request, 'File was uploaded Successfully')

            # rows = open(os.path.join(settings.BASE_DIR, 'media/documents/filename.csv'))
            # for row in csv.DictReader(rows, delimiter=","):
            #     form_data =  dataModelForm(row)
            #     if form_data.is_valid():
            #         form_data.save()
            with open(os.path.join(settings.BASE_DIR, 'media/documents/filename.csv')) as f:
                reader = csv.reader(f)
               

                for row in reader:
                    # _, created = dataModel.objects.get_or_create(
                    #     fname = row[0],
                    #     lname = row[1],
                    # )
                    _, created = studentModel.objects.get_or_create(
                        eNo                 = row[0],
                        Name                = row[1],
                        FacNo               = row[2],
                        current_standing    = row[3],
                    )
                    
                    passs, user = UserLogin.objects.get_or_create(
                        username = row[0],
                        isStudent=True,
                        # password = row[2],
                    )
                    passs.set_password(row[2])
                    passs.save()
            return HttpResponseRedirect('')
        else:
            messages.info(
                request, 'There was some issue in uploading the file please try again')
    else:
        form = DocumentForm()
    return render(request, 'dashBoardProvost/upload.html', {'form': form})


def index(request):
    return render(request, "dashBoardStudent/index.html", {})


def logged_in(request):
    return HttpResponse("SuccessFully logged in")


def login_view(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)

                return HttpResponseRedirect('/dashBoardProvost/')
            else:
                return HttpResponse("Your account is not active")
        else:
            return HttpResponse("Invalid Login Attempt")
    else:
        return render(request, "dashBoardProvost/login.html", {})



def InitializeHostelView(request):
    if request.method == 'POST':
        form = InitializeHostelForm(request.POST)
        if form.is_valid():
            # form.save()

            hostelName = str(form.cleaned_data.get("hostel_name"))
            numberOfRooms = int(form.cleaned_data.get("numberOfRooms"))
            seater = int(form.cleaned_data.get("seater"))
            room_num = 1
            seat_num = 1

            for seat in range(numberOfRooms * seater):
                
                _, instance = roomModel.objects.get_or_create(
                    hostel = hostelName,
                    seat_no = seat_num,
                    room_no = room_num,
                    seater = seater,
                    vacant = True,
                )
                seat_num = seat_num + 1

                if seat % seater == seater-1:
                    room_num = room_num + 1
                    seat_num = 1
            
            return HttpResponseRedirect('')
                # room = roomModel(
                #     hostel=hostelName,
                #     seater = seater,
                #     room_no = room+1,
                #     vacancy = seater,
                # )
                # room.save()
        else:
            messages.info(
                request, 'Invalid Form')
    else:
        form = InitializeHostelForm()
        return render(request,'dashBoardProvost/InitializeHostelForm.html',{'form': form})


def AllotmentView(request):

    if request.method == 'POST':
        
        for student in studentModel.objects.all():

            standing = student.current_standing

            if standing>=15:
                
                for room in roomModel.objects.all():
                    if room.seater == 1 and room.vacant == True:
                        room.student = student
                        room.vacant = False
                        room.save()
                        # print('1')
                        break

            elif standing>=5:

                for room in roomModel.objects.all():
                    if room.seater == 2 and room.vacant == True:
                        room.student = student
                        room.vacant = False
                        room.save()
                        # print('2')
                        break
                
            else :
                for room in roomModel.objects.all():
                    if room.seater == 4 and room.vacant == True:
                        room.student = student
                        room.vacant = False
                        room.save()
                        # print('3')
                        break
            student.current_standing+=5
            student.save()
        return HttpResponseRedirect('')
    else:
        return render(request,'dashBoardProvost/allotment.html',{})
            
               
               
            

practiceSite/dashBoardProvost/templates/dashBoardProvost/InitializeHostelForm.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'dashBoardProvost/styles.css' %}" />
    <!-- <script src="main.js"></script> -->
</head>

<body>
    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="{% url 'dashBoardProvost:provostIndex' %}">Profile</a>
        <a href="{% url 'dashBoardProvost:upload' %}">Upload CSV</a>
        <a href="{% url 'dashBoardProvost:InitializeHostelForm' %}">Initialize your hostels</a>
        <a href="{% url 'dashBoardProvost:Allotment' %}">Allot Rooms</a>
        <!-- <a href="#">Update Profile</a> -->
        <a href="#">Grievances</a>
        <a href="#">Logout</a>
    </div>

    <div id="main">
        <!-- <h2>Sidenav Push Example</h2> -->
        <!-- <p>Click on the element below to open the side navigation menu, and push this content to the right.</p> -->
        <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Provost</span>
        <div class="container-fluid" id="content-areas">
            <!-- Hello -->
            <form action="" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Initialize</button>
                {% if messages %}
                {% for message in messages %}
                <script {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                    alert(' {{ message }} ')
                </script>
                {% endfor %}
                {% endif %}
            </form>
        </div>
    </div>

    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
            document.getElementById("main").style.marginLeft = "250px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>

</body>

</html>

practiceSite/dashBoardProvost/templates/dashBoardProvost/allotment.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'dashBoardProvost/styles.css' %}" />
    <!-- <script src="main.js"></script> -->
</head>

<body>
    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="{% url 'dashBoardProvost:provostIndex' %}">Profile</a>
        <a href="{% url 'dashBoardProvost:upload' %}">Upload CSV</a>
        <a href="{% url 'dashBoardProvost:InitializeHostelForm' %}">Initialize your hostels</a>
        <a href="{% url 'dashBoardProvost:Allotment' %}">Allot Rooms</a>
        <!-- <a href="#">Update Profile</a> -->
        <a href="#">Grievances</a>
        <a href="#">Logout</a>
    </div>

    <div id="main">
        <!-- <h2>Sidenav Push Example</h2> -->
        <!-- <p>Click on the element below to open the side navigation menu, and push this content to the right.</p> -->
        <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Provost</span>
        <div class="container-fluid" id="content-areas">
            <form method="POST" action="">
                {% csrf_token %}
                <button type="submit">Allot rooms</button>
                <!-- <input type="button" value="Allot Rooms"> -->
            </form>
            <!-- Hello -->
        </div>
    </div>

    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
            document.getElementById("main").style.marginLeft = "250px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>

</body>

</html>

practiceSite/dashBoardProvost/templates/dashBoardProvost/dashboard.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'dashBoardProvost/styles.css' %}" />
    <!-- <script src="main.js"></script> -->
</head>

<body>
    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="{% url 'dashBoardProvost:provostIndex' %}">Profile</a>
        <a href="{% url 'dashBoardProvost:upload' %}">Upload CSV</a>
        <a href="{% url 'dashBoardProvost:InitializeHostelForm' %}">Initialize your hostels</a>
        <a href="{% url 'dashBoardProvost:Allotment' %}">Allot Rooms</a>
        <!-- <a href="#">Update Profile</a> -->
        <a href="#">Grievances</a>
        <a href="#">Logout</a>
    </div>

    <div id="main">
        <!-- <h2>Sidenav Push Example</h2> -->
        <!-- <p>Click on the element below to open the side navigation menu, and push this content to the right.</p> -->
        <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Welcome Provost</span>
        <div class="container-fluid" id="content-areas">
            <ul>
                <li>Please make sure that the csv file is in the following format.
                    <ul>
                        <li>Enrollment No</li>
                        <li>Name</li>
                        <li>Faculty Number</li>
                        <li>Standing</li>
                    </ul>
                </li>
                <li>Please perform the allotment int the following sequence
                    <ul>
                        <li>Upload spreadsheet in csv format with file name as 'filename.csv'</li>
                        <li>Initialize your hostels</li>
                        <li>Allot the rooms</li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>

    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
            document.getElementById("main").style.marginLeft = "250px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>

</body>

</html>

practiceSite/dashBoardProvost/templates/dashBoardProvost/login.html
<html>

<head>
    <title>Login Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<style>
    .loginBox{
            width: 250px;
            height: 300px;
            margin: 100px auto;
            box-shadow: 0px 2px 5px 5px #888888;
            border-radius: 5px;
            padding: 10px;
        }
        .topic{
            background-color:steelblue;
            color: white;
            padding: 20px;
            border-radius: 5px;
        }
    </style>

    <body>
        <div class="loginBox container-fluid">
            <div class="container-fluid topic">
                <h3>Provost's Login:</h3>
            </div>
            <hr>
            <form method='POST'>
                {% csrf_token %}
                <p>
                    <label for="username">Username :</label>
                    <input type="text" name="username">
                </p>
                <p>
                    <label for="password"> Password : </label>
                    <input type="password" name="password">
                </p>
                <hr>
                <p>
                    <input type="submit" value="Login">
                </p>
            </form>
        </div>
    </body>

</html>

practiceSite/dashBoardProvost/templates/dashBoardProvost/upload.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'dashBoardProvost/styles.css' %}" />
    <!-- <script src="main.js"></script> -->
</head>

<body>
    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="{% url 'dashBoardProvost:provostIndex' %}">Profile</a>
        <a href="{% url 'dashBoardProvost:upload' %}">Upload CSV</a>
        <a href="{% url 'dashBoardProvost:InitializeHostelForm' %}">Initialize your hostels</a>
        <a href="{% url 'dashBoardProvost:Allotment' %}">Allot Rooms</a>
        <!-- <a href="#">Update Profile</a> -->
        <a href="#">Grievances</a>
        <a href="#">Logout</a>
    </div>

    <div id="main">
        <!-- <h2>Sidenav Push Example</h2> -->
        <!-- <p>Click on the element below to open the side navigation menu, and push this content to the right.</p> -->
        <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Provost</span>
        <div class="container-fluid" id="content-areas">
            <!-- Hello -->
            {% block content %}
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %} 
                {{ form.as_p }}
                <p>Upload you .csv file</p>
                <p>Make sure the name of the file is 'filename.csv'</p>
                <button type="submit">Upload</button>
                <hr>
                <!-- <button type="submit">Update List</button> -->
            </form>
            {% if messages %}
            {% for message in messages %}
            <script {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                alert(' {{ message }} ')
            </script>
            {% endfor %}
            {% endif %}
            
            {% if messages %}
            <!-- <ul class="messages">
                {% for message in messages %}
                <li >{{ message }}</li>
                {% endfor %}
            </ul> -->
            {% endif %}
            
            <!-- <p><a href="{%  url 'fileUploads:index' %}">Return to home</a></p> -->
            {% endblock %}
        </div>
    </div>

    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
            document.getElementById("main").style.marginLeft = "250px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>

</body>

</html>