practiceSite/fileUploads/urls.py
from django.urls import path
from . import views
app_name = 'fileUploads'
urlpatterns = [
    path('',views.IndexView.as_view(),name = 'index'),
    path('upload/',views.modelFormUpload, name = 'upload'),
]

practiceSite/homepage/urls.py
from django.urls import path
from . import views
app_name='homepage'

urlpatterns=[
    path('',views.IndexView.as_view(),name='index')
]

practiceSite/practiceSite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url,include
from django.views.generic import RedirectView
from dashBoardStudent import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    #path('',RedirectView.as_view(url='/accounts/login')),
    #path('admin/', admin.site.urls),
    #path('accounts/',include('django.contrib.auth.urls')),
    # path('polls/', include('polls.urls')),
    #path('fileUploads/',include('fileUploads.urls'))

    #url(r'^dashBoardStudent/$', include(dashBoardStudent.urls))
    path('admin/', admin.site.urls),
    path('dashBoardStudent/', include('dashBoardStudent.urls')),
    path('dashBoardProvost/', include('dashBoardProvost.urls')),
    path('', RedirectView.as_view(url='/homepage/')),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('polls/', include('polls.urls')),
    path('fileUploads/', include('fileUploads.urls')),
    path('homepage/', include('homepage.urls'))
]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

practiceSite/fileUploads/models.py
from django.db import models

# Create your models here.
class Document(models.Model):
    file = models.FileField(upload_to='documents/')

practiceSite/fileUploads/forms.py
from django import forms
from .models import Document

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('file', )

practiceSite/fileUploads/views.py
from django.shortcuts import render
from .forms import DocumentForm
from django.http import HttpResponseRedirect
from django.views import generic
from django.contrib import messages
# Create your views here.
class IndexView(generic.TemplateView):
    template_name = 'fileUploads/index.html'

def modelFormUpload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            messages.info(request,'File was uploaded Successfully')
            return HttpResponseRedirect('')
        else:
            messages.info(request,'There was some issue in uploading the file please try again')
    else:
        form = DocumentForm()
    return render(request,'fileUploads/upload.html',{'form':form})

practiceSite/fileUploads/templates/fileUploads/index.html
{% block content %}
<h1>What you can do:</h1>
<li>
    <a href="{% url 'fileUploads:upload' %}">Upload a .csv file </a>
</li>
{% endblock %}

practiceSite/fileUploads/templates/fileUploads/upload.html
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %} {{ form.as_p }}
    <p>Upload you csv file</p>
    <button type="submit">Upload</button>
</form>
{% if messages %}
    {% for message in messages %}
    <script {% if message.tags %} class="{{ message.tags }}" {% endif %}>
        alert(' {{ message }} ')
    </script>
    {% endfor %}
{% endif %}

{% if messages %}
<!-- <ul class="messages">
    {% for message in messages %}
    <li >{{ message }}</li>
    {% endfor %}
</ul> -->
{% endif %}

<p><a href="{% url 'fileUploads:index' %}">Return to home</a></p>
{% endblock %}